export const METRICAS_INICIALES = {
  faseActual: 0,
  tiempoRestante: 8, // semanas
  presupuestoRestante: 100000,
  calidadProyecto: 100,
  riesgoProyecto: 20,
  satisfaccionStakeholders: 80,
  avanceProyecto: 0,
  historial: [],
  eventosDisparados: 0,
};

export const baseDatos = {
  fases: [
    { id: 0, titulo: "Bienvenida", clave: "bienvenida" },
    { id: 1, titulo: "Fase 1: Inicio", clave: "inicio", avanceObjetivo: 10 },
    {
      id: 2,
      titulo: "Fase 2: Planificación",
      clave: "planificacion",
      avanceObjetivo: 25,
    },
    {
      id: 3,
      titulo: "Fase 3: Ejecución",
      clave: "ejecucion",
      avanceObjetivo: 85,
    },
    {
      id: 4,
      titulo: "Fase 4: Monitoreo y Control",
      clave: "monitoreo",
      avanceObjetivo: 100,
    },
    { id: 5, titulo: "Fase 5: Cierre", clave: "cierre" },
  ],
  inicio: [
    {
      id: "i1",
      texto: "Definir el objetivo principal del proyecto:",
      opciones: [
        {
          texto: "Priorizar rapidez para salir al mercado",
          tiempo: 0,
          presupuesto: 0,
          calidad: -10,
          riesgo: 10,
          satisfaccion: 5,
        },
        {
          texto: "Priorizar calidad integral y adopción",
          tiempo: -1,
          presupuesto: -5000,
          calidad: 20,
          riesgo: -5,
          satisfaccion: 10,
        },
        {
          texto: "Mantener estricto apego al presupuesto",
          tiempo: 0,
          presupuesto: 5000,
          calidad: -10,
          riesgo: 5,
          satisfaccion: -5,
        },
      ],
    },
    {
      id: "i2",
      texto: "Identificar stakeholders prioritarios:",
      opciones: [
        {
          texto: "Foco en el patrocinador y reporte",
          tiempo: 0,
          presupuesto: 0,
          calidad: 0,
          riesgo: 10,
          satisfaccion: 10,
        },
        {
          texto: "Foco en los usuarios finales e involucremiento",
          tiempo: -1,
          presupuesto: -2000,
          calidad: 15,
          riesgo: -10,
          satisfaccion: 15,
        },
      ],
    },
    {
      id: "i3",
      texto: "Seleccionar criterio de éxito:",
      opciones: [
        {
          texto: "Cumplir fechas y presupuesto exacto (Predictivo)",
          tiempo: 0,
          presupuesto: 0,
          calidad: 0,
          riesgo: 0,
          satisfaccion: 0,
        },
        {
          texto: "Valor entregado y adopción (Ágil)",
          tiempo: 0,
          presupuesto: -5000,
          calidad: 10,
          riesgo: -5,
          satisfaccion: 10,
        },
      ],
    },
    {
      id: "i4",
      texto: "Validar alcance inicial:",
      opciones: [
        {
          texto: "Alcance estricto y firmado",
          tiempo: 0,
          presupuesto: 0,
          calidad: 0,
          riesgo: -15,
          satisfaccion: -5,
        },
        {
          texto: "Alcance flexible con backlog",
          tiempo: -1,
          presupuesto: 0,
          calidad: 10,
          riesgo: 15,
          satisfaccion: 5,
        },
      ],
    },
    {
      id: "i5",
      texto: "Designar enfoque de trabajo del equipo:",
      opciones: [
        {
          texto: "Formación de equipo interno",
          tiempo: -2,
          presupuesto: 10000,
          calidad: 5,
          riesgo: 10,
          satisfaccion: 5,
        },
        {
          texto: "Contratar consultoría externa rápida",
          tiempo: 1,
          presupuesto: -20000,
          calidad: 10,
          riesgo: -10,
          satisfaccion: 10,
        },
      ],
    },
  ],
  planificacion: [
    {
      id: "p1",
      texto: "Priorización del alcance:",
      opciones: [
        {
          texto: "Desarrollar todas las features solicitadas",
          tiempo: -1,
          presupuesto: -10000,
          calidad: 10,
          riesgo: 20,
          satisfaccion: 10,
        },
        {
          texto: "Desarrollar un Producto Mínimo Viable (MVP)",
          tiempo: 2,
          presupuesto: 10000,
          calidad: -10,
          riesgo: -20,
          satisfaccion: -10,
        },
      ],
    },
    {
      id: "p2",
      texto: "Estrategia de respuestas a riesgos (retraso proveedor):",
      opciones: [
        {
          texto: "Aceptar el riesgo (no hacer nada)",
          tiempo: 0,
          presupuesto: 0,
          calidad: 0,
          riesgo: 15,
          satisfaccion: 0,
        },
        {
          texto: "Mitigar (pagar póliza/urgencia)",
          tiempo: 0,
          presupuesto: -15000,
          calidad: 0,
          riesgo: -25,
          satisfaccion: 5,
        },
      ],
    },
    {
      id: "p3",
      texto: "Estrategia de comunicación:",
      opciones: [
        {
          texto: "Reportes semanales en PDF",
          tiempo: 0,
          presupuesto: 0,
          calidad: 0,
          riesgo: 5,
          satisfaccion: -5,
        },
        {
          texto: "Dashboard en tiempo real interactivo",
          tiempo: -1,
          presupuesto: -5000,
          calidad: 5,
          riesgo: -10,
          satisfaccion: 20,
        },
      ],
    },
    {
      id: "p4",
      texto: "Asignación de presupuesto (Reservas):",
      opciones: [
        {
          texto: "No guardar reserva, invertir todo",
          tiempo: 0,
          presupuesto: 0,
          calidad: 15,
          riesgo: 30,
          satisfaccion: 10,
        },
        {
          texto: "Guardar 15% como reserva de contingencia",
          tiempo: 0,
          presupuesto: -15000,
          calidad: -5,
          riesgo: -15,
          satisfaccion: 0,
        },
      ],
    },
    {
      id: "p5",
      texto: "Secuencia de actividades:",
      opciones: [
        {
          texto: "Actividades en paralelo (Fast-tracking)",
          tiempo: 2,
          presupuesto: -5000,
          calidad: -15,
          riesgo: 25,
          satisfaccion: 0,
        },
        {
          texto: "Secuencia estricta y segura",
          tiempo: -2,
          presupuesto: 0,
          calidad: 10,
          riesgo: -10,
          satisfaccion: 5,
        },
      ],
    },
  ],
  eventos: [
    {
      id: "e1",
      texto: "El proveedor principal notifica posible retraso de 2 semanas.",
      opciones: [
        {
          texto: "Pagar horas extra para compensar",
          tiempo: 0,
          presupuesto: -12000,
          calidad: 0,
          riesgo: -5,
          satisfaccion: 5,
        },
        {
          texto: "Absorber el retraso y reajustar cronograma",
          tiempo: -2,
          presupuesto: 0,
          calidad: 0,
          riesgo: 5,
          satisfaccion: -15,
        },
        {
          texto: "Presionar legalmente al proveedor",
          tiempo: -1,
          presupuesto: -2000,
          calidad: -10,
          riesgo: 15,
          satisfaccion: -5,
        },
      ],
    },
    {
      id: "e2",
      texto:
        "El patrocinador solicita una nueva funcionalidad urgente (Cambio de alcance).",
      opciones: [
        {
          texto: "Aceptar sin evaluar impacto",
          tiempo: -1,
          presupuesto: -8000,
          calidad: 5,
          riesgo: 20,
          satisfaccion: 15,
        },
        {
          texto: "Pasar por comité de control de cambios",
          tiempo: -1,
          presupuesto: 0,
          calidad: 10,
          riesgo: -10,
          satisfaccion: -5,
        },
        {
          texto: "Rechazar rotundamente",
          tiempo: 0,
          presupuesto: 0,
          calidad: 0,
          riesgo: -5,
          satisfaccion: -25,
        },
      ],
    },
    {
      id: "e3",
      texto:
        "Un miembro clave del equipo técnico reporta baja médica (1 semana).",
      opciones: [
        {
          texto: "Redistribuir tareas entre el equipo actual",
          tiempo: -1,
          presupuesto: 0,
          calidad: -15,
          riesgo: 15,
          satisfaccion: -5,
        },
        {
          texto: "Contratar freelance de emergencia",
          tiempo: 0,
          presupuesto: -10000,
          calidad: -5,
          riesgo: 10,
          satisfaccion: 0,
        },
        {
          texto: "Detener sus tareas hasta que vuelva",
          tiempo: -1,
          presupuesto: 0,
          calidad: 0,
          riesgo: 5,
          satisfaccion: -10,
        },
      ],
    },
    {
      id: "e4",
      texto: "Se halla un defecto crítico en las pruebas tempranas.",
      opciones: [
        {
          texto: "Ignorarlo y documentarlo para fase 2",
          tiempo: 0,
          presupuesto: 0,
          calidad: -30,
          riesgo: 40,
          satisfaccion: -10,
        },
        {
          texto: "Parar todo y resolverlo (Crash)",
          tiempo: -2,
          presupuesto: -5000,
          calidad: 20,
          riesgo: -10,
          satisfaccion: 5,
        },
        {
          texto: "Reducir alcance funcional para compensarlo",
          tiempo: 0,
          presupuesto: 0,
          calidad: -10,
          riesgo: -5,
          satisfaccion: -15,
        },
      ],
    },
    {
      id: "e5",
      texto:
        "Los usuarios piloto consideran que la interfaz es poco intuitiva.",
      opciones: [
        {
          texto: "Retrasar lanzamiento e invertir en UI/UX",
          tiempo: -2,
          presupuesto: -15000,
          calidad: 25,
          riesgo: -10,
          satisfaccion: 20,
        },
        {
          texto: "Lanzar con manuales de capacitación",
          tiempo: 0,
          presupuesto: -2000,
          calidad: -10,
          riesgo: 15,
          satisfaccion: -20,
        },
      ],
    },
    {
      id: "e6",
      texto: "Recorte presupuestario corporativo del 10%.",
      opciones: [
        {
          texto: "Absorber reduciendo calidad y testeos",
          tiempo: 0,
          presupuesto: 10000,
          calidad: -25,
          riesgo: 30,
          satisfaccion: -10,
        },
        {
          texto: "Reducir alcance a funciones Core",
          tiempo: 0,
          presupuesto: 10000,
          calidad: 0,
          riesgo: 5,
          satisfaccion: -15,
        },
      ],
    },
    {
      id: "e7",
      texto: "La dirección exige adelantar la entrega 1 semana.",
      opciones: [
        {
          texto: "Aceptar e inyectar recursos (Crashing)",
          tiempo: 1,
          presupuesto: -20000,
          calidad: -5,
          riesgo: 10,
          satisfaccion: 10,
        },
        {
          texto: "Negociar entrega en fases",
          tiempo: 0,
          presupuesto: 0,
          calidad: 5,
          riesgo: -5,
          satisfaccion: 0,
        },
      ],
    },
    {
      id: "e8",
      texto: "Oportunidad: Una nueva tecnología abarata costos de servidor.",
      opciones: [
        {
          texto: "Migrar a la nueva tecnología (Riesgo inicial)",
          tiempo: -1,
          presupuesto: 15000,
          calidad: 10,
          riesgo: 20,
          satisfaccion: 10,
        },
        {
          texto: "Mantenerse estables con el plan original",
          tiempo: 0,
          presupuesto: 0,
          calidad: 0,
          riesgo: -5,
          satisfaccion: 0,
        },
      ],
    },
  ],
  monitoreo: [
    {
      id: "c1",
      texto: "Acción sobre el Desempeño General:",
      opciones: [
        {
          texto: "Replanificar cronograma formalmente",
          tiempo: -1,
          presupuesto: -2000,
          calidad: 5,
          riesgo: -15,
          satisfaccion: -5,
        },
        {
          texto: "Mantener curso actual apostando a mejora natural",
          tiempo: 0,
          presupuesto: 0,
          calidad: -10,
          riesgo: 15,
          satisfaccion: -10,
        },
      ],
    },
    {
      id: "c2",
      texto: "Acción sobre Presupuesto:",
      opciones: [
        {
          texto: "Solicitar fondo de reserva al patrocinador",
          tiempo: 0,
          presupuesto: 25000,
          calidad: 0,
          riesgo: -10,
          satisfaccion: -20,
        },
        {
          texto: "Congelar contrataciones y optimizar",
          tiempo: 0,
          presupuesto: 0,
          calidad: -15,
          riesgo: 10,
          satisfaccion: 5,
        },
      ],
    },
    {
      id: "c3",
      texto: "Acción sobre Calidad:",
      opciones: [
        {
          texto: "Auditoría externa profunda",
          tiempo: -1,
          presupuesto: -8000,
          calidad: 20,
          riesgo: -20,
          satisfaccion: 10,
        },
        {
          texto: "Autoevaluación superficial",
          tiempo: 0,
          presupuesto: 0,
          calidad: -5,
          riesgo: 5,
          satisfaccion: 0,
        },
      ],
    },
    {
      id: "c4",
      texto: "Comunicación en crisis:",
      opciones: [
        {
          texto: "Transparencia total y reuniones diarias de estado",
          tiempo: -1,
          presupuesto: 0,
          calidad: 10,
          riesgo: -15,
          satisfaccion: 15,
        },
        {
          texto: "Ocultar desviaciones menores y proteger al equipo",
          tiempo: 0,
          presupuesto: 0,
          calidad: 0,
          riesgo: 25,
          satisfaccion: -15,
        },
      ],
    },
    {
      id: "c5",
      texto: "Afrontar la etapa final:",
      opciones: [
        {
          texto: "Congelamiento total de alcance (Cerrar grifo)",
          tiempo: 1,
          presupuesto: 0,
          calidad: 5,
          riesgo: -20,
          satisfaccion: -5,
        },
        {
          texto: "Permitir últimos cambios solicitados (Flexibilidad)",
          tiempo: -2,
          presupuesto: -10000,
          calidad: -10,
          riesgo: 20,
          satisfaccion: 20,
        },
      ],
    },
  ],
};
